# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schet.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 200)
        MainWindow.setMinimumSize(QtCore.QSize(600, 200))
        MainWindow.setMaximumSize(QtCore.QSize(600, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtNum1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNum1.setGeometry(QtCore.QRect(70, 60, 131, 41))
        self.txtNum1.setObjectName("txtNum1")
        self.txtNum2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNum2.setGeometry(QtCore.QRect(220, 60, 121, 41))
        self.txtNum2.setObjectName("txtNum2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 65, 81, 31))
        self.label.setObjectName("label")
        self.setText = QtWidgets.QLabel(self.centralwidget)
        self.setText.setGeometry(QtCore.QRect(400, 60, 121, 41))
        self.setText.setText("")
        self.setText.setObjectName("setText")
        self.getResult = QtWidgets.QPushButton(self.centralwidget)
        self.getResult.setGeometry(QtCore.QRect(70, 120, 271, 51))
        self.getResult.setObjectName("getResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "="))
        self.getResult.setText(_translate("MainWindow", "ВЫПОЛНИТЬ"))
